version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w

archives:
  - formats:
      - binary

changelog:
  sort: desc

release:
  draft: false
